apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-mysql
spec:
  selector:
    matchLabels:
      app: spire-mysql
      type: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spire-mysql
        type: database
    spec:
      containers:
        - image: mysql:8.0
          name: spire-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spire-mysql-password
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: spire-mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: spire-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: spire-mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: spire-mysql-initdb-config