apiVersion: v1
kind: PersistentVolume
metadata:
  name: spire-mysql-pv
  labels:
    app: spire-server
    type: database
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"