apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spire-mysql-pv-claim
  labels:
    app: spire-server
    type: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi