apiVersion: v1
data:
  server.conf: |
    server {
      admin_ids = ["spiffe://accuknox.com/saas/cluster-onboarding", "spiffe://accuknox.com/saas/cluster-management"]
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "accuknox.com"
      data_dir = "/run/spire-server"
      log_level = "DEBUG"
      default_x509_svid_ttl = "1h" 
      default_jwt_svid_ttl = "1h"
      ca_ttl = "6h"
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire-server/spire.sqlite3"
        }
      }

      NodeAttestor "join_token" {
        plugin_data {
        }
      }

      KeyManager "disk" {
        plugin_data = {
          keys_path = "/run/spire-server/keys.json"
        }
      }

      UpstreamAuthority "disk" {
        plugin_data {
          key_file_path =  "/run/spire/ca/upstream_ca.key"
          cert_file_path = "/run/spire/ca/upstream_ca.crt"
        }
      }

    }
    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "9090"
      live_path = "/live"
      ready_path = "/ready"
    }
kind: ConfigMap
metadata:
  labels:
    app: spire-server
  name: spire-server
