apiVersion: v1
kind: Service
metadata:
  labels:
    app: spire-server
  name: spire-server
spec:
  ports:
    - name: grpc
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: health
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: spire-server
  type: ClusterIP
