apiVersion: v1
data:
  app.yaml: |-
    app:
      wait-time: 300      # wait time in seconds
    spire:
      down-time: 3000    # down time in seconds to generate token
      agent-health: spire-agent:9090/live
      server-health: spire-server:9090/live
      agentID: spiffe://accuknox.com/saas/agent
      secret-name: "spire-agent-secret"
      configmap-name: "spire-agent"
      namespace: spire
kind: ConfigMap
metadata:
  labels:
    app: spire-server
  name: spire-sidecar-config
