apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: spire-server
  name: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      containers:
        - args:
            - '-config'
            - /run/spire-server/config/server.conf
          image: knoxuser/spire:server
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /live
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 3
          name: spire-server
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /run/spire-server/config
              name: spire-server-config
              readOnly: true
            - mountPath: /tmp/spire-server/private
              name: spire-server-socket
            - mountPath: /run/spire/ca
              name: certs
              readOnly: true
        - command:
            - /spire-sidecar/sidecar
          image: knoxuser/spire:sidecar
          imagePullPolicy: IfNotPresent
          name: spire-sidecar
          resources: {}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  cp /run/spire-server/config/entry.sh /tmp && chmod +x
                  /tmp/entry.sh && /tmp/entry.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /tmp/spire-server/private
              name: spire-server-socket
            - mountPath: /run/spire-server/config
              name: spire-server-default-entry
              readOnly: true
            - mountPath: /spire-sidecar/config
              name: spire-sidecar-config
              readOnly: true
      serviceAccount: spire-server
      serviceAccountName: spire-server
      volumes:
        - configMap:
            defaultMode: 420
            name: spire-server
          name: spire-server-config
        - configMap:
            defaultMode: 420
            name: spire-server-default-entry
          name: spire-server-default-entry
        - emptyDir: {}
          name: spire-server-socket
        - name: certs
          secret:
            defaultMode: 420
            secretName: certs
        - configMap:
            defaultMode: 420
            name: spire-sidecar-config
          name: spire-sidecar-config
