apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spire-server
  name: spire-server-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spire-server-config
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: spire
