apiVersion: v1
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      server_address = "spire-server.spire.svc.cluster.local"
      server_port = "8081"
      agent_address = "0.0.0.0"
      agent_port = "9091"
      insecure_bootstrap = true
      trust_domain = "accuknox.com"
      join_token = "02a25013-60fc-494a-b142-7e503ed09c1f"
    }

    plugins {
      NodeAttestor "join_token" {
        plugin_data {
        }
      }
      KeyManager "keymanager-k8s" {
        plugin_cmd = "/config/plugin/keymanager-k8s"
        plugin_data {
          namespace = "spire"
          secretname = "spire-agent-secret"
        }
      }
      WorkloadAttestor "k8s_sat" {
        plugin_cmd = "/config/plugin/k8s-sat"
        plugin_data {
        }
      }
    }
    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "9090"
      live_path = "/live"
      ready_path = "/ready"
    }
kind: ConfigMap
metadata:
  labels:
    app: spire-agent
  name: spire-agent
