apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: spire-agent
  name: spire-agent
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - nodes
      - nodes/proxy
      - secrets
      - tokenreviews
      - configmaps
      - pods/exec
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update
