apiVersion: v1
kind: Service
metadata:
  labels:
    app: spire-agent
  name: spire-agent
spec:
  ports:
    - name: grpc
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: health
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: spire-agent
  type: ClusterIP
